name: transfer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  transfer:
    runs-on: ubuntu-latest
    environment: transfer
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          curl -O https://dlcdn.apache.org/flink/flink-1.12.7/flink-1.12.7-bin-scala_2.12.tgz
          ls
      - uses: actions/setup-python@v3.1.2
      - name: install cos
        run: |
          ls
          pip install coscmd
          pip install coscmd -U
      - name: config cos
        env:
          COS_A: ${{ secrets.COS_A }}
          COS_S: ${{ secrets.COS_S }}
          COS_B: ${{ secrets.COS_B }}
          COS_R: ${{ secrets.COS_R }}
        run : |
          echo "$COS_R"
          coscmd config -a "$COS_A" -s "$COS_S" -b "$COS_B" -r "$COS_R"
          cat /home/runner/.cos.conf
          coscmd upload  flink-1.12.7-bin-scala_2.12.tgz /wall-download/flink-1.12.7-bin-scala_2.12.tgz
