name: transfer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.2-linux-x86_64.tar.gz
          ls
  upload:
    runs-on: ubuntu-latest
    environment: transfer
    steps:
      - uses: actions/setup-python@v3.1.2
      - name: install cos
        run: |
          ls
          pip install coscmd
          pip install coscmd -U
      - name: config cos
        env:
          COS_A: ${{ secrets.COS_A }}
          COS_S: ${{ secrets.COS_S }}
          COS_B: ${{ secrets.COS_B }}
          COS_R: ${{ secrets.COS_R }}
        run : |
          coscmd config -a "$COS_A" -s "$COS_S" -b "$COS_B" -r "$COS_R"
          coscmd upload  elasticsearch-7.13.2-linux-x86_64.tar.gz /wall-download/elasticsearch-7.13.2-linux-x86_64.tar.gz
